openapi: 3.2.0
info:
  title: Postmark Outbound API
  description: 'Postmark helps deliver and track application email. In a nutshell, the

    service replaces SMTP (or Sendmail) with a far more reliable, scalable and

    care-free environment. In addition, you can track statistics such as

    number of emails sent or processed, opens, bounces and spam complaints.'
  version: 1.0.0
servers:
- url: http://{{baseurl}}
tags:
- name: Outbound
paths:
  /stats/outbound/clicks:
    get:
      tags:
      - Outbound
      summary: Postmark Get click counts
      parameters:
      - name: tag
        in: query
        schema:
          type: string
        description: Filter by tag
        example: <string>
      - name: fromdate
        in: query
        schema:
          type: string
        description: Filter messages starting from the date specified. e.g. `2014-02-01`
        example: <string>
      - name: todate
        in: query
        schema:
          type: string
        description: Filter messages up to the date specified. e.g. `2014-02-01`
        example: <string>
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getStatsOutboundClicks
      x-operation-id-source: derived
  /stats/outbound/clicks/platforms:
    get:
      tags:
      - Outbound
      summary: Postmark Get browser plaform usage
      parameters:
      - name: tag
        in: query
        schema:
          type: string
        description: Filter by tag
        example: <string>
      - name: fromdate
        in: query
        schema:
          type: string
        description: Filter messages starting from the date specified. e.g. `2014-02-01`
        example: <string>
      - name: todate
        in: query
        schema:
          type: string
        description: Filter messages up to the date specified. e.g. `2014-02-01`
        example: <string>
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getStatsOutboundClicksPlatforms
      x-operation-id-source: derived
  /stats/outbound/opens:
    get:
      tags:
      - Outbound
      summary: Postmark Get email open counts
      parameters:
      - name: tag
        in: query
        schema:
          type: string
        description: Filter by tag
        example: <string>
      - name: fromdate
        in: query
        schema:
          type: string
        description: Filter messages starting from the date specified. e.g. `2014-02-01`
        example: <string>
      - name: todate
        in: query
        schema:
          type: string
        description: Filter messages up to the date specified. e.g. `2014-02-01`
        example: <string>
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getStatsOutboundOpens
      x-operation-id-source: derived
  /stats/outbound/opens/platforms:
    get:
      tags:
      - Outbound
      summary: Postmark Get email platform usage
      parameters:
      - name: tag
        in: query
        schema:
          type: string
        description: Filter by tag
        example: <string>
      - name: fromdate
        in: query
        schema:
          type: string
        description: Filter messages starting from the date specified. e.g. `2014-02-01`
        example: <string>
      - name: todate
        in: query
        schema:
          type: string
        description: Filter messages up to the date specified. e.g. `2014-02-01`
        example: <string>
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getStatsOutboundOpensPlatforms
      x-operation-id-source: derived
  /stats/outbound/opens/readtimes:
    get:
      tags:
      - Outbound
      summary: Postmark Get email read times
      parameters:
      - name: tag
        in: query
        schema:
          type: string
        description: Filter by tag
        example: <string>
      - name: fromdate
        in: query
        schema:
          type: string
        description: Filter messages starting from the date specified. e.g. `2014-02-01`
        example: <string>
      - name: todate
        in: query
        schema:
          type: string
        description: Filter messages up to the date specified. e.g. `2014-02-01`
        example: <string>
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getStatsOutboundOpensReadtimes
      x-operation-id-source: derived
  /stats/outbound:
    get:
      tags:
      - Outbound
      summary: Postmark Get outbound overview
      parameters:
      - name: tag
        in: query
        schema:
          type: string
        description: Filter by tag
        example: <string>
      - name: fromdate
        in: query
        schema:
          type: string
        description: Filter messages starting from the date specified. e.g. `2014-02-01`
        example: <string>
      - name: todate
        in: query
        schema:
          type: string
        description: Filter messages up to the date specified. e.g. `2014-02-01`
        example: <string>
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getStatsOutbound
      x-operation-id-source: derived
  /stats/outbound/bounces:
    get:
      tags:
      - Outbound
      summary: Postmark Get bounce counts
      parameters:
      - name: tag
        in: query
        schema:
          type: string
        description: Filter by tag
        example: <string>
      - name: fromdate
        in: query
        schema:
          type: string
        description: Filter messages starting from the date specified. e.g. `2014-02-01`
        example: <string>
      - name: todate
        in: query
        schema:
          type: string
        description: Filter messages up to the date specified. e.g. `2014-02-01`
        example: <string>
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getStatsOutboundBounces
      x-operation-id-source: derived
  /stats/outbound/sends:
    get:
      tags:
      - Outbound
      summary: Postmark Get sent counts
      parameters:
      - name: tag
        in: query
        schema:
          type: string
        description: Filter by tag
        example: <string>
      - name: fromdate
        in: query
        schema:
          type: string
        description: Filter messages starting from the date specified. e.g. `2014-02-01`
        example: <string>
      - name: todate
        in: query
        schema:
          type: string
        description: Filter messages up to the date specified. e.g. `2014-02-01`
        example: <string>
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getStatsOutboundSends
      x-operation-id-source: derived
  /stats/outbound/spam:
    get:
      tags:
      - Outbound
      summary: Postmark Get spam complaints
      parameters:
      - name: tag
        in: query
        schema:
          type: string
        description: Filter by tag
        example: <string>
      - name: fromdate
        in: query
        schema:
          type: string
        description: Filter messages starting from the date specified. e.g. `2014-02-01`
        example: <string>
      - name: todate
        in: query
        schema:
          type: string
        description: Filter messages up to the date specified. e.g. `2014-02-01`
        example: <string>
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getStatsOutboundSpam
      x-operation-id-source: derived
  /stats/outbound/tracked:
    get:
      tags:
      - Outbound
      summary: Postmark Get tracked email counts
      parameters:
      - name: tag
        in: query
        schema:
          type: string
        description: Filter by tag
        example: <string>
      - name: fromdate
        in: query
        schema:
          type: string
        description: Filter messages starting from the date specified. e.g. `2014-02-01`
        example: <string>
      - name: todate
        in: query
        schema:
          type: string
        description: Filter messages up to the date specified. e.g. `2014-02-01`
        example: <string>
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getStatsOutboundTracked
      x-operation-id-source: derived
