openapi: 3.2.0
info:
  title: Postmark Triggers API
  description: 'Postmark helps deliver and track application email. In a nutshell, the

    service replaces SMTP (or Sendmail) with a far more reliable, scalable and

    care-free environment. In addition, you can track statistics such as

    number of emails sent or processed, opens, bounces and spam complaints.'
  version: 1.0.0
servers:
- url: http://{{baseurl}}
tags:
- name: Triggers
paths:
  /triggers/inboundrules:
    get:
      tags:
      - Triggers
      summary: Postmark List inbound rule triggers
      parameters:
      - name: count
        in: query
        schema:
          type: string
        description: Number of bounces to return per request. Max 500.
        example: <integer>
      - name: offset
        in: query
        schema:
          type: string
        description: Number of bounces to skip.
        example: <integer>
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getTriggersInboundrules
      x-operation-id-source: derived
  /triggers/tags:
    get:
      tags:
      - Triggers
      summary: Postmark Search triggers
      parameters:
      - name: count
        in: query
        schema:
          type: string
        description: Number of bounces to return per request. Max 500.
        example: <integer>
      - name: offset
        in: query
        schema:
          type: string
        description: Number of bounces to skip.
        example: <integer>
      - name: match_name
        in: query
        schema:
          type: string
        description: Filter by delivery tag
        example: <string>
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getTriggersTags
      x-operation-id-source: derived
  /triggers/tags/{triggerid}:
    delete:
      tags:
      - Triggers
      summary: Postmark Delete a single trigger
      parameters:
      - name: triggerid
        in: path
        schema:
          type: string
        required: true
        description: The ID of the Inbound Rule that should be deleted.
        example: <integer>
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: deleteTriggersTagsByTriggerid
      x-operation-id-source: derived
