openapi: 3.2.0
info:
  title: Postmark Templates API
  description: 'Postmark helps deliver and track application email. In a nutshell, the

    service replaces SMTP (or Sendmail) with a far more reliable, scalable and

    care-free environment. In addition, you can track statistics such as

    number of emails sent or processed, opens, bounces and spam complaints.'
  version: 1.0.0
servers:
- url: http://{{baseurl}}
tags:
- name: Templates
paths:
  /templates:
    get:
      tags:
      - Templates
      summary: Postmark Get the Templates associated with this Server
      parameters:
      - name: count
        in: query
        schema:
          type: string
        description: Number of bounces to return per request. Max 500.
        example: <integer>
      - name: offset
        in: query
        schema:
          type: string
        description: Number of bounces to skip.
        example: <integer>
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getTemplates
      x-operation-id-source: derived
  /templates/validate:
    post:
      tags:
      - Templates
      summary: Postmark Test Template Content
      requestBody:
        content: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: postTemplatesValidate
      x-operation-id-source: derived
